# pytest.ini

[pytest]
# Adiciona o diretório raiz do projeto ao PYTHONPATH.
# Isso permite que os testes importem módulos como 'from app.core.config import settings'.
python_files = test_*.py
addopts = --strict-markers
pythonpath = .